### ISSUE TITLE
Imaginary component error in FID code when using fewer images (<2048)

### ISSUE THREAD

**Issue by badhri-intel** [ahmadki/mlperf_sd_inference#4]
When we run FID script with using fewer generated images (typically < 2048 images), the covariance matrix has complex numbers and it raises the following error. 

Traceback (most recent call last):
  File "fid_score.py", line 260, in <module>
    args.dims)
  File "fid_score.py", line 248, in calculate_fid_given_paths
    fid_value = calculate_frechet_distance(m1, s1, m2, s2)
  File "fid_score.py", line 184, in calculate_frechet_distance
    raise ValueError('Imaginary component {}'.format(m))
ValueError: Imaginary component 0.6888144870124462

This is a bug in the FID code as mentioned [here](https://github.com/mseitzer/pytorch-fid/issues/13). @ahmadki Please let us know how you are able to calculate valid FID scores for much fewer samples (100 samples for instance)?

**Comment by khansharkhamnida** [comment]
Any solutions?

**Comment by badhri-intel** [comment]
scipy==1.9.1 fixes this issue. I have created the PR

**Comment by ahmadki** [comment]
should be fixed with https://github.com/ahmadki/mlperf_sd_inference/pull/5 merged. Thank you @badhri-intel
